(ns app.data)


(def data [{:role "Frontend",
            :postedAt "1d ago",
            :logo "./images/photosnap.svg",
            :new true,
            :contract "Full Time",
            :tools [],
            :featured true,
            :level "Senior",
            :id 1,
            :position "Senior Frontend Developer",
            :languages ["HTML" "CSS" "JavaScript"],
            :location "USA Only",
            :company "Photosnap"}
           {:role "Fullstack",
            :postedAt "1d ago",
            :logo "./images/manage.svg",
            :new true,
            :contract "Part Time",
            :tools ["React"],
            :featured true,
            :level "Midweight",
            :id 2,
            :position "Fullstack Developer",
            :languages ["Python"],
            :location "Remote",
            :company "Manage"}
           {:role "Frontend",
            :postedAt "2d ago",
            :logo "./images/account.svg",
            :new true,
            :contract "Part Time",
            :tools ["React" "Sass"],
            :featured false,
            :level "Junior",
            :id 3,
            :position "Junior Frontend Developer",
            :languages ["JavaScript"],
            :location "USA Only",
            :company "Account"}
           {:role "Frontend",
            :postedAt "5d ago",
            :logo "./images/myhome.svg",
            :new false,
            :contract "Contract",
            :tools [],
            :featured false,
            :level "Junior",
            :id 4,
            :position "Junior Frontend Developer",
            :languages ["CSS" "JavaScript"],
            :location "USA Only",
            :company "MyHome"}
           {:role "FullStack",
            :postedAt "1w ago",
            :logo "./images/loop-studios.svg",
            :new false,
            :contract "Full Time",
            :tools ["Ruby" "Sass"],
            :featured false,
            :level "Midweight",
            :id 5,
            :position "Software Engineer",
            :languages ["JavaScript"],
            :location "Worldwide",
            :company "Loop Studios"}
           {:role "Backend",
            :postedAt "2w ago",
            :logo "./images/faceit.svg",
            :new false,
            :contract "Full Time",
            :tools ["RoR"],
            :featured false,
            :level "Junior",
            :id 6,
            :position "Junior Backend Developer",
            :languages ["Ruby"],
            :location "UK Only",
            :company "FaceIt"}
           {:role "Frontend",
            :postedAt "2w ago",
            :logo "./images/shortly.svg",
            :new false,
            :contract "Full Time",
            :tools ["Sass"],
            :featured false,
            :level "Junior",
            :id 7,
            :position "Junior Developer",
            :languages ["HTML" "JavaScript"],
            :location "Worldwide",
            :company "Shortly"}
           {:role "Frontend",
            :postedAt "2w ago",
            :logo "./images/insure.svg",
            :new false,
            :contract "Full Time",
            :tools ["Vue" "Sass"],
            :featured false,
            :level "Junior",
            :id 8,
            :position "Junior Frontend Developer",
            :languages ["JavaScript"],
            :location "USA Only",
            :company "Insure"}
           {:role "Fullstack",
            :postedAt "3w ago",
            :logo "./images/eyecam-co.svg",
            :new false,
            :contract "Full Time",
            :tools ["Django"],
            :featured false,
            :level "Midweight",
            :id 9,
            :position "Full Stack Engineer",
            :languages ["JavaScript" "Python"],
            :location "Worldwide",
            :company "Eyecam Co."}
           {:role "Frontend",
            :postedAt "1mo ago",
            :logo "./images/the-air-filter-company.svg",
            :new false,
            :contract "Part Time",
            :tools ["React" "Sass"],
            :featured false,
            :level "Junior",
            :id 10,
            :position "Front-end Dev",
            :languages ["JavaScript"],
            :location "Worldwide",
            :company "The Air Filter Company"}])